version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  app:
    build: .
    ports:
      - "3049:3049"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Collector HTTP endpoint
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
volumes:
  redis_data:
