# Jaeger configuration for Docker Compose
version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - "16686:16686" # Jaeger UI
      - "6831:6831/udp" # Jaeger agent (UDP)
      - "14268:14268" # Jaeger collector (HTTP)
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
